applikasiDlm/protected/modules/manajemendata/controllers/BiodataController.php
<?php

class BiodataController extends DlmController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$bantuanModalDataProvider =new CActiveDataProvider('BantuanModal', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));
		
		$bantuanSosialDataProvider =new CActiveDataProvider('BantuanSosial', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));
		
		$bantuanLainnyaDataProvider =new CActiveDataProvider('BantuanLainnya', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));

		$riwayatKesehatanDataProvider=new CActiveDataProvider('RiwayatKesehatan', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));
		
		$riwayatPekerjaanDataProvider=new CActiveDataProvider('RiwayatPekerjaan', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));
		
		$riwayatPendidikanDataProvider=new CActiveDataProvider('RiwayatPendidikan', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$id),
			),
		));
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'bantuanModalDataProvider'=>$bantuanModalDataProvider,
			'bantuanSosialDataProvider'=>$bantuanSosialDataProvider,
			'bantuanLainnyaDataProvider'=>$bantuanLainnyaDataProvider,
			'riwayatKesehatanDataProvider'=>$riwayatKesehatanDataProvider,
			'riwayatPekerjaanDataProvider'=>$riwayatPekerjaanDataProvider,
			'riwayatPendidikanDataProvider'=>$riwayatPendidikanDataProvider,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Biodata;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Biodata']))
		{
			$model->attributes=$_POST['Biodata'];
			$model->tgl_lhr = Utils::toOracleDateFormat($model->tgl_lhr);
			if(!Utils::IsNullOrEmpty($model->tgl_kwn)){
				$model->tgl_kwn = Utils::toOracleDateFormat($model->tgl_kwn);		
			}	
			
			if(!Utils::IsNullOrEmpty($model->tgl_crai)){
				$model->tgl_crai = Utils::toOracleDateFormat($model->tgl_crai);	
			}	
				
			if(!Utils::IsNullOrEmpty($model->tgl_meninggal)){
				$model->tgl_meninggal = Utils::toOracleDateFormat($model->tgl_meninggal);	
			}
			
			if($model->save())
				$this->redirect(array('view','id'=>$model->nik));
		}
		
		if(Utils::IsNullOrEmpty($model->akta_lhr)){
			$model->akta_lhr = 2;
		}
		
		if(Utils::IsNullOrEmpty($model->stat_kwn)){
			$model->stat_kwn = 1;
		}
		
		if(Utils::IsNullOrEmpty($model->akta_kwn)){
			$model->akta_kwn = 2;
		}
		
		if(Utils::IsNullOrEmpty($model->akta_crai)){
			$model->akta_crai = 2;
		}
		
		if(Utils::IsNullOrEmpty($model->pnydng_cct)){
			$model->pnydng_cct = 2;
		}
		
		if(Utils::IsNullOrEmpty($model->stat_hidup)){
			$model->stat_hidup = 2;
		}
		
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Biodata']))
		{
			$model->attributes=$_POST['Biodata'];
			$model->tgl_lhr = Utils::toOracleDateFormat($model->tgl_lhr);
			if(!Utils::IsNullOrEmpty($model->tgl_kwn)){
				$model->tgl_kwn = Utils::toOracleDateFormat($model->tgl_kwn);		
			}	
			
			if(!Utils::IsNullOrEmpty($model->tgl_crai)){
				$model->tgl_crai = Utils::toOracleDateFormat($model->tgl_crai);	
			}	
				
			if(!Utils::IsNullOrEmpty($model->tgl_meninggal)){
				$model->tgl_meninggal = Utils::toOracleDateFormat($model->tgl_meninggal);	
			}		
			
			if($model->save())
				$this->redirect(array('view','id'=>$model->nik));
		}
		
		$model->tgl_lhr = Utils::fromOracleDateFormat($model->tgl_lhr);	
		$model->tgl_kwn = Utils::fromOracleDateFormat($model->tgl_kwn);	
		$model->tgl_crai = Utils::fromOracleDateFormat($model->tgl_crai);	
		
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Biodata('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Biodata'])){
			$model->attributes=$_GET['Biodata'];

			// $nmJenKel = $_GET['Biodata']['nama_jenis_kelamin'];
			// $model->attributes->jenis_kelamin = 1;//array_search($nmJenKel, $model->getJenisKelaminOptions());

		}

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Biodata::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='biodata-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

applikasiDlm/protected/modules/manajemendata/controllers/RiwayatPekerjaanController.php
<?php

class RiwayatPekerjaanController extends DlmController
{
	private $_biodata;
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'BiodataContext + create update',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new RiwayatPekerjaan;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['RiwayatPekerjaan']))
		{
			$model->attributes=$_POST['RiwayatPekerjaan'];
			if($model->save())
				$this->redirect(array('update','id'=>$model->id, "nik"=>$model->nik));
		}
		
		$model->nik = $this->_biodata->nik;
		$model->nama_penduduk = $this->_biodata->nama_lgkp;
		$model->no_kk = $this->_biodata->no_kk;
		
		$riwayatDataProvider=new CActiveDataProvider('RiwayatPekerjaan', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$this->_biodata->nik),
			),
		));
		
		$this->render('create',array(
			'model'=>$model,
			'riwayatDataProvider'=>$riwayatDataProvider,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id, $ajax="")
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['RiwayatPekerjaan']))
		{
			$model->attributes=$_POST['RiwayatPekerjaan'];
			if($model->save())
				$this->redirect(array('update','id'=>$model->id, "nik"=>$model->nik));
		}
		
		$riwayatDataProvider=new CActiveDataProvider('RiwayatPekerjaan', array(
			'criteria'=>array(
			'condition'=>'"nik"=:nik',
			'params'=>array(':nik'=>$this->_biodata->nik),
			),
		));
		
		$this->render('update',array(
			'model'=>$model,
			'riwayatDataProvider'=>$riwayatDataProvider,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax'])){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
				//$this->redirect(array('create', "nik"=>$nik));
			}
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Manages all models.

	public function actionIndex()
	{
		$model=new RiwayatPekerjaan('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['RiwayatPekerjaan']))
			$model->attributes=$_GET['RiwayatPekerjaan'];

		$this->render('index',array(
			'model'=>$model,
		));
	}	 */

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=RiwayatPekerjaan::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='riwayat-pekerjaan-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/* load biodata */
	private function loadBiodata($nik) {
		if($this->_biodata===null)
		{
			$this->_biodata=Biodata::model()->findbyPk($nik);
			if($this->_biodata===null)
			{
				throw new CHttpException(404,'NIK tidak valid.'); 
			}
		}
		return $this->_biodata; 
	} 
	
	/* filter Biodata */
	public function filterBiodataContext($filterChain)
	{ 
		$nik = null;
		if(isset($_GET['nik'])) {
			$nik = $_GET['nik'];
		}else{
			if(isset($_POST['nik'])) 
				$nik = $_POST['nik'];
		}
		
		$this->loadBiodata($nik); 
		
		$filterChain->run(); 
	}

}

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'riwayat-pekerjaan-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block"><?php echo Yii::t('dlm', 'required field'); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'nik',array('class'=>'span5', 'readonly'=>'readonly')); ?>
	
	<?php echo $form->textFieldRow($model,'nama_penduduk',array('class'=>'span5', 'readonly'=>'readonly')); ?>
	
	<?php echo $form->textFieldRow($model,'no_kk',array('class'=>'span5', 'readonly'=>'readonly')); ?>

	<?php echo $form->textFieldRow($model,'nama_pekerjaan',array('class'=>'span5', 'autocomplete'=>'off', 'append'=>'<i class="icon-search"></i>')); ?>
	
	<?php echo $form->hiddenField($model,'id_pek'); ?>

	<?php echo $form->textFieldRow($model,'tempat_bekerja',array('class'=>'span5','maxlength'=>200)); ?>

	<?php echo $form->textFieldRow($model,'rata_penghasilan',array('class'=>'span5')); ?>

	<?php echo $form->datepickerRow($model, 'tahun',
        array('append'=>'<i class="icon-calendar"></i>', 'class'=>'span1', 'options'=>array(
    		'format'=>'yyyy',
    		'viewMode'=>'years',
    		'minViewMode'=>'years',
    		'autoclose'=>'true',
    	)));
	?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Simpan',
		)); ?>
		
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'link',
			'type'=>'danger',
			'label'=>'Batal',
			'url'=>'/manajemendata/biodata/update/id/'.$model->nik,
		)); ?>
		
		<?php 
		if(!$model->isNewRecord ){
			$this->widget('bootstrap.widgets.TbButton', array(
				'buttonType'=>'link',
				'type'=>'primary',
				'label'=>'+ Buat Riwayat Pekerjaan Baru',
				'url' => '/manajemendata/riwayatpekerjaan/create/nik/' . $model->nik,
			));
		} 
		?>
	</div>

<?php $this->endWidget(); ?>

<script type="text/javascript">
	$(function(){
		if($("#RiwayatPekerjaan_nama_pekerjaan").size()> 0){
			$("#RiwayatPekerjaan_nama_pekerjaan").keyup(function(){
				parameter = "term=" + $('#RiwayatPekerjaan_nama_pekerjaan').val();
			});
			TextFieldAutoComplete("/general/getPekerjaan", "RiwayatPekerjaan_nama_pekerjaan", "RiwayatPekerjaan_id_pek");
		}
	});
</script>

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'nik',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'id_pek',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tempat_bekerja',array('class'=>'span5','maxlength'=>200)); ?>

	<?php echo $form->textFieldRow($model,'rata_penghasilan',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tahun',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'userid',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tglinput',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tglupdate',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/create.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Riwayat Pekerjaan'=>array('index'),
	'Tambah',
);

$this->menu=array(
	array('label'=>'Kembali','url'=>array('biodata/update', 'id'=>$model->nik)),
	//array('label'=>'Daftar Biodata','url'=>array('biodata/index')),
);
?>

<h1>Tambah Riwayat Pekerjaan</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

<br/>
	<span class="section-block">Daftar Riwayat Pekerjaan</span>
	<?php $this->widget('bootstrap.widgets.TbGridView',array(
		'id'=>'riwayat-pekerjaan-details-grid',
		'dataProvider'=>$riwayatDataProvider,
		'template' => "{items}",
		'enableSorting' => false,
		'columns'=>array(
			'no_kk',
			'nik',
			'nama_penduduk',
			'nama_pekerjaan',
			'tempat_bekerja',
			'rata_penghasilan',
			'tahun',
			array(
				'class'=>'bootstrap.widgets.TbButtonColumn',
				'template'=>'{update} {delete}'
			),
		),
	)); ?>
	
	
<script type="text/javascript">
	$(function(){	
		$(".update, .delete").each(function(){
			var strUrl = $(this).attr("href") + "/nik/"+<?php echo $model->nik; ?>+"";
			
			$(this).attr("href", strUrl);
		});
	});
</script>

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/index.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Riwayat Pekerjaans'=>array('index'),
	'Daftar',
);

$this->menu=array(
	array('label'=>'Tambah Biodata','url'=>array('biodata/create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('riwayat-pekerjaan-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Daftar Riwayat Pekerjaan</h1>
<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'riwayat-pekerjaan-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'nik',
		'id_pek',
		'tempat_bekerja',
		'rata_penghasilan',
		'tahun',
		/*
		'userid',
		'tglinput',
		'tglupdate',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/update.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Riwayat Pekerjaan'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Ubah',
);

$this->menu=array(
	array('label'=>'Kembali','url'=>array('biodata/update', 'id'=>$model->nik)),
	//array('label'=>'Daftar Biodata','url'=>array('biodata/index')),
	//array('label'=>'Tambah Biodata','url'=>array('biodata/create')),
	//array('label'=>'Detil RiwayatPekerjaan','url'=>array('view','id'=>$model->id)),
);
?>

<h1>Ubah Riwayat Pekerjaan </h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

<br/>
	<span class="section-block">Daftar Riwayat Pekerjaan</span>
	<?php $this->widget('bootstrap.widgets.TbGridView',array(
		'id'=>'riwayat-pekerjaan-details-grid',
		'dataProvider'=>$riwayatDataProvider,
		'template' => "{items}",
		'enableSorting' => false,
		'columns'=>array(
			'no_kk',
			'nik',
			'nama_penduduk',
			'nama_pekerjaan',
			'tempat_bekerja',
			'rata_penghasilan',
			'tahun',
			array(
				'class'=>'bootstrap.widgets.TbButtonColumn',
				'template'=>'{update} {delete}'
			),
		),
	)); ?>
	
	
<script type="text/javascript">
	$(function(){	
		$(".update, .delete").each(function(){
			var strUrl = $(this).attr("href") + "/nik/"+<?php echo $model->nik; ?>+"";
			
			$(this).attr("href", strUrl);
		});
	});
</script>

applikasiDlm/protected/modules/manajemendata/views/riwayatPekerjaan/view.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Riwayat Pekerjaan'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'Daftar RiwayatPekerjaan','url'=>array('index')),
	array('label'=>'Tambah RiwayatPekerjaan','url'=>array('create')),
	array('label'=>'Ubah RiwayatPekerjaan','url'=>array('update','id'=>$model->id)),
	array('label'=>'Hapus RiwayatPekerjaan','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>Yii::t('dlm', 'confirm delete'))),
);
?>

<h1>Detil RiwayatPekerjaan</h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'nik',
		'id_pek',
		'tempat_bekerja',
		'rata_penghasilan',
		'tahun',
		'userid',
		'tglinput',
		'tglupdate',
	),
)); ?>