applikasiDlm/protected/modules/manajemendata/controllers/ArtikelController.php
<?php

class ArtikelController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('togglevisibility','delete'),
				'users'=>array('superadmin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Artikel;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Artikel']))
		{
			if(Yii::app()->user->name == 'superadmin'){
				$_POST['Artikel']['is_visible'] = '1';
			}else{
				$_POST['Artikel']['is_visible'] = '0';
			}
			
			//FB::info(Yii::app()->user);

			$_POST['Artikel']['userid'] = Yii::app()->user->id;
			$_POST['Artikel']['tglinput'] = date('d-M-y');

			$model->attributes=$_POST['Artikel'];

			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Artikel']))
		{
			$_POST['Artikel']['tglupdate'] = date('d-M-y');

			$model->attributes=$_POST['Artikel'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
     * @throws CHttpException
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Artikel('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Artikel']))
			$model->attributes=$_GET['Artikel'];
		$this->render('index',array(
			'model'=>$model,
		));
	}

	public function actionTogglevisibility($id, $status)
	{
		$visibility = 0;
		if((bool)!$status){
			$visibility = 1;
		}

		$model = new Artikel;
		$model->updateVisibility($id, $visibility);
		//$this->redirect(array('index'));

		// $model = $this->loadModel((int)$id);
		// $model->attributes = array('is_visible'=>$visibility);
		$model->save();
		// if($model->save())
		// 	CVarDumper::Dump($model->getErrors(),100,true);
			// $this->redirect(array('index'));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
     * @return mixed
     * @throws CHttpException
     */
    public function loadModel($id)
	{
		$model=Artikel::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		//convert clob to string
		// $model->text_intro = stream_get_contents($model->text_intro);
		// $model->text_full = stream_get_contents($model->text_full);
		$model->text_intro = $model->text_intro->load();
		$model->text_full = $model->text_full->load();
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='artikel-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

applikasiDlm/protected/modules/manajemendata/views/artikel/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'artikel-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block"><?php echo Yii::t('dlm', 'required field'); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model, 'title', array(
		'class'=>'span5'
	)); ?>

	<?php echo $form->html5EditorRow($model,'text_intro',array('class'=>'span5','maxlength'=>500, 'height'=>'100px', 'width'=>'98%')); ?>

	<?php echo $form->ckEditorRow($model,'text_full',array('class'=>'span5','maxlength'=>4000)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Simpan',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

applikasiDlm/protected/modules/manajemendata/views/artikel/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'text_intro',array('class'=>'span5','maxlength'=>4000)); ?>

	<?php echo $form->textFieldRow($model,'text_full',array('class'=>'span5','maxlength'=>4000)); ?>

	<?php echo $form->textFieldRow($model,'is_visible',array('class'=>'span5','maxlength'=>2000)); ?>

	<?php echo $form->textFieldRow($model,'userid',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tglinput',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tglupdate',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

applikasiDlm/protected/modules/manajemendata/views/artikel/create.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Artikel'=>array('index'),
	'Tambah Artikel',
);

$this->menu=array(
	array('label'=>'Daftar Artikel','url'=>array('index')),
);
?>

<h1>Tambah Artikel</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

applikasiDlm/protected/modules/manajemendata/views/artikel/index.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Artikels'=>array('index'),
	'Daftar',
);

$this->menu=array(
	array('label'=>'Tambah Artikel','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('artikel-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Daftar Artikel</h1>

<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'artikel-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		// 'id',
		// 'text_intro',
		// 'text_full',
		'title',
		array(
			'name'=>'is_visible',
			'type'=>'boolean',
			'value'=>'$data->is_visible',
			'filter'=>array('1'=>'Yes', '0'=>'No')
		),
		
		// array(
		// 	'name'=>'is_visible',
		// 	'type'=>'raw',
		// 	'value'=>array('Ya'=>1, 'Tidak'=>0),
		// ),
		array(
			'name'=>'user.username',
			'value'=>'$data->user->username',
			'header'=>'Pengirim'
		),
		array(
			'name'=>'tglinput',
		),
		// 'tglupdate',
		
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
		array(
			'class'=>'CLinkColumn',
			'labelExpression'=>'$data->checkVisibility($data)',
			'urlExpression'=>'array("artikel/togglevisibility", "id"=>$data->id, "status"=>$data->is_visible)',
			'linkHtmlOptions'=>array(
				'url'=>'artikel',
			),
		),
		// array(
	 //        'header'=>'Actions',
	 //        'type'=>'raw',
	 //        'value'=>'CHtml::ajaxLink(CHtml::image("' . Yii::app()->request->baseUrl . '/path/to/icon.png", "Delete", array("title"=>"Delete","class"=>"grid_icon")), Yii::app()->createUrl("controller/ajaxDelete"), array("type"=>"POST", "data"=>array("id"=>$data->id, "action"=>"delete"), "success"=>"jsDelete"), array("onclick"=>"$(\'.grid-view\').addClass(\'grid-view-loading\')", "class"=>"delete", "confirm"=>"Are you sure?\r\nDrafts are permanently deleted and are not recoverable.") )',
		// ),			
	),
)); ?>

applikasiDlm/protected/modules/manajemendata/views/artikel/update.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Artikel'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Ubah',
);

$this->menu=array(
	array('label'=>'Daftar Artikel','url'=>array('index')),
	array('label'=>'Tambah Artikel','url'=>array('create')),
	array('label'=>'Detil Artikel','url'=>array('view','id'=>$model->id)),
);
?>

<h1>Ubah Artikel <small><?php echo $model->title; ?></small></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

applikasiDlm/protected/modules/manajemendata/views/artikel/view.php
<?php
$this->breadcrumbs=array(
	ucfirst($this->module->id)=>'/'.$this->module->id,
	'Artikel'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'Daftar Artikel','url'=>array('index')),
	array('label'=>'Tambah Artikel','url'=>array('create')),
	array('label'=>'Ubah Artikel Ini','url'=>array('update','id'=>$model->id)),
	array('label'=>'Hapus Artikel Ini','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Anda yakin menghapus item ini?')),
);
?>


<div class="page-header">
	<h1><?php echo $model->title; ?> <small>dikirim <?php echo date('d-m-Y',strtotime($model->tglinput)); ?></small></h1>
	<?php if((bool)$model->is_visible):?>
	<div class=""><span class="label label-info pull-right">Dipublikasi!</span></div>
	<?php else: ?>
	<div class=""><span class="label label-important pull-right">Tidak dipublikasi!</span></div>
	<?php endif; ?>
</div>

<?php echo '<p>' . $model->text_intro . '</p>'; ?>
<?php echo $model->text_full; ?>